# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Recipe.create(recipe_name: 'Gruyere Grilled Cheese with Caramelized Onions', ingredients: '1 small sweet onion, thinly sliced, 2 tablespoons olive oil, Pinch salt, Pinch sugar, Sliced hearty whole-grain bread, Gruyere Cheese, sliced', instructions: 'Take two pieces of bread line one side with sliced cheese. Then distribute some onions over top and top with another piece of bread. Brush the outside pieces with olive oil and return to the pan. I recommend placing another pan on top of the sandwich in order to squash it down a bit. Cook the sandwich until the bread has browned, about 2-5 minutes. Flip over and repeat. Transfer to a plate and dig in!')
Recipe.create(recipe_name: 'Lasagna', ingredients: '1 pound sweet Italian sausage, 3/4 pound lean ground beef, 1/2 cup minced onion, 2 cloves garlic, crushed, 1 28-ounce can crushed tomatoes, 2 6-ounce cans tomato sauce, 1/2 cup water 2 tablespoons white sugar, 1 1/2 teaspoons dried basil leaves, 1/2 teaspoon fennel seeds, 1 teaspoon Italian seasoning, 1 tablespoon salt, 1/4 teaspoon ground black pepper, 4 tablespoons chopped fresh parsley, 12 lasagna noodles, 16 ounces ricotta cheese, 1 egg, 1/2 teaspoon salt, 3/4 pound mozzarella cheese, sliced, 3/4 cup Parmesan cheese, grated', instructions: 'In a Dutch oven, cook sausage, ground beef, onion, and garlic over medium heat until well browned. Stir in crushed tomatoes, tomato paste, tomato sauce, and water. Season with sugar, basil, fennel seeds, Italian seasoning, 1 tablespoon salt, pepper, and 2 tablespoons parsley. Simmer, covered, for about 1 1/2 hours, stirring occasionally. Bring a large pot of lightly salted water to a boil. Cook lasagna noodles in boiling water for 8 to 10 minutes. Drain noodles, and rinse with cold water. In a mixing bowl, combine ricotta cheese with egg, remaining parsley, and 1/2 teaspoon salt. Preheat oven to 375 degrees F (190 degrees C). To assemble, spread 1 1/2 cups of meat sauce in the bottom of a 9x13 inch baking dish. Arrange 6 noodles lengthwise over meat sauce. Spread with one half of the ricotta cheese mixture. Top with a third of mozzarella cheese slices. Spoon 1 1/2 cups meat sauce over mozzarella, and sprinkle with 1/4 cup Parmesan cheese. Repeat layers, and top with remaining mozzarella and Parmesan cheese. Cover with foil: to prevent sticking, either spray foil with cooking spray, or make sure the foil does not touch the cheese. Bake in preheated oven for 25 minutes. Remove foil, and bake an additional 25 minutes. Cool for 15 minutes before serving.')
